language: node_js
node_js:
  - '8'
  - '10'

after_script:
  - npm run coveralls

deploy:
  provider: npm
  email: thaiat@ipelia.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    node: '8'
    repo: Yoobic/cordova-config